# Generated by Django 4.2.1 on 2023-06-10 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='experimentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
